// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebQuery.DataBaseEntity;

#nullable disable

namespace WebQuery.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241217095538_InstallQuery")]
    partial class InstallQuery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebQuery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Вх_N")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Заказчик")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("На_сервере")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Объект")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ответственный")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Предмет_запроса")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Примечание")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Реестр_ТКП")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
